// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// from_json
List from_json(const char* json);
RcppExport SEXP _baidugeo_from_json(SEXP jsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type json(jsonSEXP);
    rcpp_result_gen = Rcpp::wrap(from_json(json));
    return rcpp_result_gen;
END_RCPP
}
// parse_api_json_coords
List parse_api_json_coords(Environment& coord_hash_map, CharacterVector& keys);
RcppExport SEXP _baidugeo_parse_api_json_coords(SEXP coord_hash_mapSEXP, SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment& >::type coord_hash_map(coord_hash_mapSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type keys(keysSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_api_json_coords(coord_hash_map, keys));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_baidugeo_from_json", (DL_FUNC) &_baidugeo_from_json, 1},
    {"_baidugeo_parse_api_json_coords", (DL_FUNC) &_baidugeo_parse_api_json_coords, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_baidugeo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
