# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_coords_from_uri <- function(uri, curr_input_lon, curr_input_lat) {
    invisible(.Call(`_baidugeo_get_coords_from_uri`, uri, curr_input_lon, curr_input_lat))
}

is_json_parsable <- function(json) {
    .Call(`_baidugeo_is_json_parsable`, json)
}

get_message_value <- function(json) {
    .Call(`_baidugeo_get_message_value`, json)
}

from_json <- function(json) {
    .Call(`_baidugeo_from_json`, json)
}

parse_api_json_coords <- function(coord_hash_map, keys) {
    .Call(`_baidugeo_parse_api_json_coords`, coord_hash_map, keys)
}

parse_api_json_addrs <- function(addr_hash_map, keys) {
    .Call(`_baidugeo_parse_api_json_addrs`, addr_hash_map, keys)
}

