# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

from_json <- function(json) {
    .Call(`_baidugeo_from_json`, json)
}

parse_api_json_coords <- function(coord_hash_map, keys) {
    .Call(`_baidugeo_parse_api_json_coords`, coord_hash_map, keys)
}

